import { type NextPage } from "next";
import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.isSignedIn ? (
        <UserButton afterSignOutUrl="/" />
      ) : (
        <Link href="sign-in" className="rounded-md bg-black p-2 text-white">
          Sign in
        </Link>
      )}
    </>
  );
};

export default Home;
