import { type NextPage } from "next";
import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (!data && !isLoading) {
    return <div>No posts yet.</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl ">
          <div className="border-b border-slate-200 p-4">
            {user.isSignedIn ? (
              <UserButton afterSignOutUrl="/" />
            ) : (
              <Link
                href="sign-in"
                className="rounded-md bg-black p-2 text-white"
              >
                Sign in
              </Link>
            )}
          </div>

          <div className="space-y-4">
            <h1 className="text-5xl font-extrabold">Posts</h1>
            <div className="flex flex-col ">
              {!data && isLoading ? (
                <p>Loading...</p>
              ) : (
                data?.map((post) => (
                  <div key={post.id} className="border-b border-slate-400 p-8">
                    {post.content}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
